In [1]:
#%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import glob

# Loading databases

In [2]:
# Take out the nan entries

def NanOff(df):
    new = pd.DataFrame(df)
    new = new.replace(np.nan,float('-1'))
    return new

In [3]:
# Number of entries array
Entries = np.array([])
EntriesCuts = np.array([])

DFrameArray = []
DFrameArrayCuts = []

FileNames = []

def OneDataFrame():
    
    for f in glob.glob('Databases/*.xls'):
        df = pd.read_excel(f,sheet_name='hoja1')
        df = NanOff(df) # TAKE OUT THE NAN ENTRIES
        
        DFrameArray.append(df)
        FileNames.append(f)
        
    dft = pd.concat(DFrameArray,ignore_index='True')
    
    return dft

In [4]:
# each element in DFrameArray is a dataframe for each section

# The index 4 contains all the information
DFrameArray.append(OneDataFrame())
DFrameArrayCuts = DFrameArray[:] #  Do slicing properly

print(id(DFrameArray))
print(id(DFrameArrayCuts))

139734336964800
139734337466240


In [5]:
Entries = np.array([])

for i in range(len(FileNames)+1):
    Entries = np.append(Entries, DFrameArray[i]['ID'].count())
    if i != 4:
        print(FileNames[i])
# Total entries in each group
print(Entries)

Databases/202110_10468_Lista de clase_16.xls
Databases/202110_39380_Lista de clase_17.xls
Databases/202110_39422_Lista de clase_19.xls
Databases/202110_39384_Lista de clase_18.xls
[23. 21. 20. 21. 85.]


In [6]:
DFrameArray[4].describe()

ID      Nota1         A1         B1         C1    D1    E1  \
count  8.500000e+01  85.000000  85.000000  85.000000  85.000000  85.0  85.0   
mean   2.019522e+08   3.290588   0.672941   0.527059   0.272941  -1.0  -1.0   
std    1.343301e+05   1.107617   0.180863   0.218974   0.308371   0.0   0.0   
min    2.014233e+08   0.000000   0.000000   0.000000   0.000000  -1.0  -1.0   
25%    2.019209e+08   2.500000   0.600000   0.500000   0.000000  -1.0  -1.0   
50%    2.020131e+08   3.500000   0.700000   0.500000   0.000000  -1.0  -1.0   
75%    2.020211e+08   4.000000   0.800000   0.600000   0.500000  -1.0  -1.0   
max    2.021134e+08   5.000000   1.000000   1.000000   1.000000  -1.0  -1.0   

         F1  Nota2    A2    B2    C2    D2    E2    F2  
count  85.0   85.0  85.0  85.0  85.0  85.0  85.0  85.0  
mean   -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  
std     0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0  
min    -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  
25%    -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  
50%    -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  
75%    -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  
max    -1.0   -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0

# Descriptive Statistics

In [7]:
Names = ['Nota','A','B','C']

NNotas = 1

DictMean = {}
DictStd = {}

for i in Names:  # Cathegories
    
    for j in range(1,NNotas+1): # Grades
        
        Name_ = i + str(j)
        
        print('Calculating for: '+Name_)

        Mean = np.array([])
        Std = np.array([])


        for k in range(len(FileNames)+1):
            Mean = np.append(Mean,np.average(DFrameArray[k][Name_]))
            Std = np.append(Std,np.std(DFrameArray[k][Name_]))
        
        DictMean[Name_] = Mean
        DictStd[Name_] = Std

Calculating for: Nota1
Calculating for: A1
Calculating for: B1
Calculating for: C1


In [8]:
# Print Dictionaries

for i in DictMean.keys():
    print(i+':')
    print(DictMean[i])
    print(DictStd[i])

A1:
[0.6        0.67142857 0.66       0.76666667 0.67294118]
[0.18177865 0.18553105 0.19595918 0.0942809  0.17979612]
C1:
[0.26521739 0.30952381 0.225      0.29047619 0.27294118]
[0.30872627 0.31305676 0.3284433  0.2670915  0.3065513 ]
Nota1:
[2.67391304 3.5047619  3.365      3.68095238 3.29058824]
[1.14785902 1.00828765 1.23502024 0.6122706  1.1010822 ]
B1:
[0.46521739 0.52380952 0.56       0.56666667 0.52705882]
[0.2883366  0.14769583 0.23537205 0.13915847 0.21768203]


# Cuts

In [26]:
def GetCuts(Cuts_):
    
    EntriesCuts = np.array([])
    
    Keys = Cuts_.keys()
    Values = Cuts_.values()
    
    for i in range(len(FileNames)+1):
    
        # Set of cuts
        Cut0 = DFrameArray[i][Keys[0]] >= Values[0]
        Cut1 = DFrameArray[i][Keys[1]] >= Values[1]
        Cut2 = DFrameArray[i][Keys[2]] >= Values[2]
        Cut3 = DFrameArray[i][Keys[3]] >= Values[3]
    
        DFrameArrayCuts[i] = DFrameArray[i][(Cut0) & (Cut1) & (Cut2) & (Cut3)]    
        # Get the new number of entries
        EntriesCuts = np.append(EntriesCuts, DFrameArrayCuts[i]['ID'].count())


    # Array of efficiencies
    Efficiencies = EntriesCuts/Entries

    #Testing 
    #print(EntriesCuts, Entries)
        
    return Efficiencies

In [27]:
Cuts = {'Nota1':3.0, 'A1':0.5, 'B1': 0.5, 'C1':0.}
Efficiencies = GetCuts(Cuts)
print(Efficiencies)

# Closure Test
#for i in range(len(FileNames)+1):
#    print(DFrameArrayCuts[i]['ID'].count())

#print(Entries)

[0.39130435 0.85714286 0.75       0.85714286 0.70588235]


# Plotting

In [28]:
def CreateGroupFig(Input,Cuts,grupo,variable):
    
    
    if Cuts:
        print('-- Calculating with Cuts ---', variable)
    else:
        print('-- Calculating ---', variable)
    
    DFrame = Input[:]
    
    fig = plt.figure(figsize=(10,10))

    ax1 = fig.add_subplot(2,2,1)
    if len(DFrame[0].index) != 0:
        ax1 = DFrame[0].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=5)
    #ax1.set_xlabel(grupo, fontsize=12)
    ax1.set_ylabel(variable, fontsize=12)

    ax2 = fig.add_subplot(2,2,2)
    if len(DFrame[1].index) != 0:
        ax2 = DFrame[1].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=5)
    #ax2.set_xlabel(grupo, fontsize=12)
    #ax2.set_ylabel(variable, fontsize=12)

    ax3 = fig.add_subplot(2,2,3)
    if len(DFrame[2].index) != 0:
        ax3 = DFrame[2].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=5)
    ax3.set_xlabel(grupo, fontsize=7)
    ax3.set_ylabel(variable, fontsize=12)

    ax4 = fig.add_subplot(2,2,4)
    if len(DFrame[3].index) != 0:
        ax4 = DFrame[3].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=5)
    ax4.set_xlabel(grupo, fontsize=7)
    #ax4.set_ylabel(variable, fontsize=12)

    Name = 'Figures/' + grupo + '_' + variable + '.pdf'
    if Cuts:
        Name = 'Figures/' + grupo + '_' + variable + '_Cuts.pdf'
        
    plt.savefig(Name,dpi=100,bbox_inches='tight')
    plt.close()

    fig = plt.figure(figsize=(10,10))
    ax1 = fig.add_subplot(1,1,1)
    if len(DFrame[4].index) != 0:
        ax1 = DFrame[4].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=5)
    ax1.set_xlabel(grupo, fontsize=7)
    ax1.set_ylabel(variable, fontsize=12)
    
    NameT = 'Figures/' + grupo + '_' + variable + '_T.pdf'
    if Cuts:
        NameT = 'Figures/' + grupo + '_' + variable + '_T_Cuts.pdf'
    
    plt.savefig(NameT,dpi=100,bbox_inches='tight')
    plt.close()

In [29]:
# Plotting using group by

grupo = 'ID'  # Variable que agrupa

for i in Names:  # Cathegories
    
    for j in range(1,NNotas+1): # Grades
        
        Name_ = i + str(j)
        
        CreateGroupFig(DFrameArray, False, grupo, Name_)
        CreateGroupFig(DFrameArrayCuts, True, grupo, Name_)

('-- Calculating ---', 'Nota1')
('-- Calculating with Cuts ---', 'Nota1')
('-- Calculating ---', 'A1')
('-- Calculating with Cuts ---', 'A1')
('-- Calculating ---', 'B1')
('-- Calculating with Cuts ---', 'B1')
('-- Calculating ---', 'C1')
('-- Calculating with Cuts ---', 'C1')


In [ ]:
# Uso de filtros por columna
#DFrameArray[0].filter(items=['ID','A1','A2'])
#DFrameArray[1].filter(like='A',axis=1)


# Seleccion por filar
#DFrameArray[2].set_index('A1')

#print(DFrameArray[2].loc[0:3])
#print(DFrameArray[2].iloc[:,0:2])

#print(DFrameArray[0]['Nota1'])
#print(dft['A1'])

In [ ]:
plt.hist(dft['B1'])
#plt.hist(DFrameArray[0]['Nota1'], density = True)
plt.show()

In [ ]:
# Agregar columna

Sum = 0

for i in range(1,2):
    Sum += DFrameArray[0]['A'+str(i)]

dtest = DFrameArray[0].assign(NotaFinal=Sum.values)
print(dtest)

In [ ]:
# Mirar posicion
print(dtest.iat[0,1])
# Cambiar posicion
##dtest.iat[0,1] = 3.
#print(dtest)


# Agregar columna o fila 
#dtest.loc['Suma x columna'] = dtest.sum(axis=0)
#dtest.loc[:,'Suma x Renglon'] = dtest.sum(axis=1)
#print(dtest)

In [ ]:
#Select the information by columns
for i in range(1,2):
    print(DFrameArray[2]['A'+str(i)])

In [ ]:
# Vamos a hacer corte

print(DFrameArray[2][DFrameArray[2]['A1']<0.7])
A1 = DFrameArray[2]['A1']
A1 = np.array(A1)
print(A1)

In [ ]:
# Plotting pies


sizes = DFrameArray[0]['A1'].value_counts()
print(sizes)
pie = DFrameArray[0]['A1'].value_counts().plot(kind='pie', shadow=True,\
                                              autopct='%1.1f%%', startangle=30,\
                                              radius=1.5,center=(0.5,0.5),\
                                              textprops={'fontsize':12},frame=False,\
                                              pctdistance=0.65)
pie.set_ylabel('')
pie.set_xlabel('')


labels=sizes.index.unique()
plt.gca().axis('equal')
plt.title(DFrameArray[0].columns[3], weight='bold',size=14)
plt.legend(labels, bbox_to_anchor=(0.,1.1))


plt.savefig('Figures/A1.pdf',dpi=100,bbox_inches='tight')


In [ ]:
# plotting using group by

fig = plt.figure(figsize=(10,10))

dft.groupby('Nota1')['A1'].sum().plot(kind='bar',legend='Reverse')
#DFrameArray[1].groupby('Nota1')['A1'].sum().plot(kind='bar',legend='Reverse')

plt.xlabel('ID')
plt.ylabel('Competencia')
plt.savefig('Figures/A1Bars.pdf',dpi=100,bbox_inches='tight')

In [ ]:
fig = plt.figure()

DFrameArray[2].A2.groupby(DFrameArray[2].ID).sum().plot(kind='pie',cmap='viridis')
plt.axis('equal')
plt.ylabel('')
plt.savefig('Figures/A1Pie.pdf',dpi=100,bbox_inches='tight')

In [ ]:
#fig = plt.figure()
sns.lmplot(x='ID',y='A1',data=DFrameArray[2],fit_reg=False,hue='ID',legend=False,palette='viridis')
#plt.savefig('Figures/A1seaborn.pdf',dpi=100,bbox_inches='tight')

In [ ]:
#sns.set(style='ticks', color_codes=True)
#g = sns.pairplot(DFrameArray[2], hue='ID', palette='Spectral')

In [ ]:
print(dft['A2'])

In [ ]:
# Write the whole dataframe in an excel file


output = pd.ExcelWriter('DataBaseFisicaI.xls')
dft.to_excel(output,'Hoja1')
output.save()