In [1]:
#%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy.stats import norm
import scipy.stats

import glob

# Loading databases

In [2]:
# Take out the nan entries

def NanOff(df):
    new = pd.DataFrame(df)
    new = new.replace(np.nan,float('-1'))
    return new

In [3]:
# Number of entries array
Entries = np.array([])
EntriesCuts = np.array([])

DFrameArray = []
DFrameArrayCuts = []

FileNames = []

def OneDataFrame():
    
    for f in glob.glob('Databases/*.xls'):
        df = pd.read_excel(f,sheet_name='hoja1')
        df = NanOff(df) # TAKE OUT THE NAN ENTRIES
        
        DFrameArray.append(df)
        FileNames.append(f)
        
    dft = pd.concat(DFrameArray,ignore_index='True')
    
    return dft

In [4]:
# each element in DFrameArray is a dataframe for each section

# The index 4 contains all the information
DFrameArray.append(OneDataFrame())
DFrameArrayCuts = DFrameArray[:] #  Do slicing properly

print(id(DFrameArray))
print(id(DFrameArrayCuts))

139907373029352
139907373530288


In [5]:
Entries = np.array([])

for i in range(len(FileNames)+1):
    Entries = np.append(Entries, DFrameArray[i]['ID'].count())
    if i != 4:
        print(FileNames[i])
# Total entries in each group
print(Entries)

Databases/202110_10468_Lista de clase_16.xls
Databases/202110_39380_Lista de clase_17.xls
Databases/202110_39422_Lista de clase_19.xls
Databases/202110_39384_Lista de clase_18.xls
[23. 21. 20. 21. 85.]


In [6]:
DFrameArray[4].describe()

ID      Nota1         A1         B1         C1    D1    E1  \
count  8.500000e+01  85.000000  85.000000  85.000000  85.000000  85.0  85.0   
mean   2.019522e+08   3.290588   0.672941   0.527059   0.272941  -1.0  -1.0   
std    1.343301e+05   1.107617   0.180863   0.218974   0.308371   0.0   0.0   
min    2.014233e+08   0.000000   0.000000   0.000000   0.000000  -1.0  -1.0   
25%    2.019209e+08   2.500000   0.600000   0.500000   0.000000  -1.0  -1.0   
50%    2.020131e+08   3.500000   0.700000   0.500000   0.000000  -1.0  -1.0   
75%    2.020211e+08   4.000000   0.800000   0.600000   0.500000  -1.0  -1.0   
max    2.021134e+08   5.000000   1.000000   1.000000   1.000000  -1.0  -1.0   

         F1      Nota2         A2  ...         D4         E4         F4  \
count  85.0  85.000000  85.000000  ...  85.000000  85.000000  85.000000   
mean   -1.0   3.335294   0.704706  ...   0.574118   0.548235   0.389412   
std     0.0   1.258467   0.208113  ...   0.257346   0.280566   0.332388   
min    -1.0   0.000000   0.000000  ...   0.000000   0.000000   0.000000   
25%    -1.0   2.500000   0.700000  ...   0.500000   0.400000   0.000000   
50%    -1.0   3.500000   0.700000  ...   0.700000   0.700000   0.300000   
75%    -1.0   4.400000   0.800000  ...   0.700000   0.700000   0.700000   
max    -1.0   5.000000   0.900000  ...   0.900000   0.900000   0.900000   

           Nota5         A5         B5         C5    D5    E5    F5  
count  85.000000  85.000000  85.000000  85.000000  85.0  85.0  85.0  
mean    3.960000   0.685882   0.597647   0.582353  -1.0  -1.0  -1.0  
std     1.567771   0.256419   0.280296   0.297280   0.0   0.0   0.0  
min     0.000000   0.000000   0.000000   0.000000  -1.0  -1.0  -1.0  
25%     4.000000   0.700000   0.400000   0.400000  -1.0  -1.0  -1.0  
50%     4.500000   0.800000   0.700000   0.700000  -1.0  -1.0  -1.0  
75%     5.000000   0.800000   0.800000   0.800000  -1.0  -1.0  -1.0  
max     5.000000   0.900000   0.900000   0.900000  -1.0  -1.0  -1.0  

[8 rows x 36 columns]

# Descriptive Statistics

In [7]:
Names = ['Nota','A','B','C','D','E','F']

NNotas = 3

DictMean = {}
DictStd = {}

for i in Names:  # Cathegories
    
    for j in range(1,NNotas+1): # Grades
        
        Name_ = i + str(j)
        
        print('Calculating for: '+Name_)

        Mean = np.array([])
        Std = np.array([])


        for k in range(len(FileNames)+1):
            Mean = np.append(Mean,np.average(DFrameArray[k][Name_]))
            Std = np.append(Std,np.std(DFrameArray[k][Name_]))
        
        DictMean[Name_] = Mean
        DictStd[Name_] = Std

Calculating for: Nota1
Calculating for: Nota2
Calculating for: Nota3
Calculating for: A1
Calculating for: A2
Calculating for: A3
Calculating for: B1
Calculating for: B2
Calculating for: B3
Calculating for: C1
Calculating for: C2
Calculating for: C3
Calculating for: D1
Calculating for: D2
Calculating for: D3
Calculating for: E1
Calculating for: E2
Calculating for: E3
Calculating for: F1
Calculating for: F2
Calculating for: F3


In [8]:
# Print Dictionaries

for i in DictMean.keys():
    print(i+':')
    print(DictMean[i])
    print(DictStd[i])

F1:
[-1. -1. -1. -1. -1.]
[0. 0. 0. 0. 0.]
F2:
[-1. -1. -1. -1. -1.]
[0. 0. 0. 0. 0.]
F3:
[-1. -1. -1. -1. -1.]
[0. 0. 0. 0. 0.]
Nota1:
[2.67391304 3.5047619  3.365      3.68095238 3.29058824]
[1.14785902 1.00828765 1.23502024 0.6122706  1.1010822 ]
Nota3:
[4.15217391 3.97142857 3.74       4.35238095 4.06      ]
[1.26038971 1.46974013 1.46812806 0.64484701 1.27391938]
Nota2:
[3.26956522 3.54285714 2.855      3.65714286 3.33529412]
[1.03269794 1.18223816 1.48002534 1.14541381 1.25104247]
E1:
[-1. -1. -1. -1. -1.]
[0. 0. 0. 0. 0.]
A1:
[0.6        0.67142857 0.66       0.76666667 0.67294118]
[0.18177865 0.18553105 0.19595918 0.0942809  0.17979612]
A3:
[0.6826087  0.68571429 0.59       0.67142857 0.65882353]
[0.27131271 0.27130323 0.31128765 0.1484615  0.26044944]
A2:
[0.74347826 0.71428571 0.635      0.71904762 0.70470588]
[0.109648   0.18331787 0.28857408 0.20146853 0.20688495]
B1:
[0.46521739 0.52380952 0.56       0.56666667 0.52705882]
[0.2883366  0.14769583 0.23537205 0.13915847 0.217

# Cuts

In [9]:
def GetCuts(Cuts_):
    
    EntriesCuts = np.array([])

    
    for i in range(len(FileNames)+1):
    
        # Set of cuts
        Cut0 = DFrameArray[i]['Nota1'] >= Cuts_['Nota1']
        Cut1 = DFrameArray[i]['A1'] >= Cuts_['A1']
        #Cut2 = DFrameArray[i][Keys[2]] >= Values[2]
        Cut2 = True
        #Cut3 = DFrameArray[i][Keys[3]] >= Values[3]
        Cut3 = True
    
        DFrameArrayCuts[i] = DFrameArray[i][(Cut0) & (Cut1)]    
        # Get the new number of entries
        EntriesCuts = np.append(EntriesCuts, DFrameArrayCuts[i]['ID'].count())


    # Array of efficiencies
    Efficiencies = EntriesCuts/Entries
    
    #Testing 
    #print(EntriesCuts, Entries)
        
    return Efficiencies, EntriesCuts

In [10]:
Cuts = {'Nota1':3.0, 'A1': 0.5, 'B1': 0., 'C1':0.}
Efficiencies, EntriesCuts = GetCuts(Cuts)
print(EntriesCuts)
print(Efficiencies)

# Closure Test
for i in range(len(FileNames)+1):
    print(DFrameArrayCuts[i]['ID'].count())

#print(Entries)

[ 9. 18. 15. 20. 62.]
[0.39130435 0.85714286 0.75       0.95238095 0.72941176]
9
18
15
20
62


In [11]:
#print(DFrameArrayCuts[4])

# Plotting

In [12]:
def CreateGroupFig(Input,Cuts,grupo,variable):
    
    Font1 = 8
    Font2 = 12
    
    if Cuts:
        print('-- Plotting with Cuts ---', variable)
    else:
        print('-- Plotting ---', variable)
    
    DFrame = Input[:]
    
    # Plots for each sample
    fig = plt.figure(figsize=(10,10))

    ax1 = fig.add_subplot(2,2,1)
    if len(DFrame[0].index) != 0:
        ax1 = DFrame[0].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=Font1)
    #ax1.set_xlabel(grupo, fontsize=Font2)
    ax1.set_ylabel(variable, fontsize=Font2)

    ax2 = fig.add_subplot(2,2,2)
    if len(DFrame[1].index) != 0:
        ax2 = DFrame[1].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=Font1)
    #ax2.set_xlabel(grupo, fontsize=Font2)
    #ax2.set_ylabel(variable, fontsize=Font2)

    ax3 = fig.add_subplot(2,2,3)
    if len(DFrame[2].index) != 0:
        ax3 = DFrame[2].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=Font1)
    ax3.set_xlabel(grupo, fontsize=Font2)
    ax3.set_ylabel(variable, fontsize=Font2)

    ax4 = fig.add_subplot(2,2,4)
    if len(DFrame[3].index) != 0:
        ax4 = DFrame[3].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=Font1)
    ax4.set_xlabel(grupo, fontsize=Font2)
    #ax4.set_ylabel(variable, fontsize=Font2)

    Name = 'Figures/Groups/' + grupo + '_' + variable + '.pdf'
    if Cuts:
        Name = 'Figures/Groups/' + grupo + '_' + variable + '_Cuts.pdf'
        
    plt.savefig(Name,dpi=100,bbox_inches='tight')
    plt.close()

    # Plot for the whole sample
    fig = plt.figure(figsize=(10,10))
    ax1 = fig.add_subplot(1,1,1)
    if len(DFrame[4].index) != 0:
        ax1 = DFrame[4].groupby(grupo)[variable].sum().plot(kind='bar', fontsize=Font1)
    ax1.set_xlabel(grupo, fontsize=Font2)
    ax1.set_ylabel(variable, fontsize=Font2)
    
    NameT = 'Figures/Groups/' + grupo + '_' + variable + '_T.pdf'
    if Cuts:
        NameT = 'Figures/Groups/' + grupo + '_' + variable + '_T_Cuts.pdf'
    
    plt.savefig(NameT,dpi=100,bbox_inches='tight')
    plt.close()

In [13]:
# Plotting using group by

grupo = 'ID'  # Variable que agrupa

for i in Names:  # Cathegories
    
    for j in range(1,NNotas+1): # Grades
        
        Name_ = i + str(j)
        
        CreateGroupFig(DFrameArray, False, grupo, Name_)
        CreateGroupFig(DFrameArrayCuts, True, grupo, Name_)

('-- Plotting ---', 'Nota1')
('-- Plotting with Cuts ---', 'Nota1')
('-- Plotting ---', 'Nota2')
('-- Plotting with Cuts ---', 'Nota2')
('-- Plotting ---', 'Nota3')
('-- Plotting with Cuts ---', 'Nota3')
('-- Plotting ---', 'A1')
('-- Plotting with Cuts ---', 'A1')
('-- Plotting ---', 'A2')
('-- Plotting with Cuts ---', 'A2')
('-- Plotting ---', 'A3')
('-- Plotting with Cuts ---', 'A3')
('-- Plotting ---', 'B1')
('-- Plotting with Cuts ---', 'B1')
('-- Plotting ---', 'B2')
('-- Plotting with Cuts ---', 'B2')
('-- Plotting ---', 'B3')
('-- Plotting with Cuts ---', 'B3')
('-- Plotting ---', 'C1')
('-- Plotting with Cuts ---', 'C1')
('-- Plotting ---', 'C2')
('-- Plotting with Cuts ---', 'C2')
('-- Plotting ---', 'C3')
('-- Plotting with Cuts ---', 'C3')
('-- Plotting ---', 'D1')
('-- Plotting with Cuts ---', 'D1')
('-- Plotting ---', 'D2')
('-- Plotting with Cuts ---', 'D2')
('-- Plotting ---', 'D3')
('-- Plotting with Cuts ---', 'D3')
('-- Plotting ---', 'E1')
('-- Plotting with Cuts --

# Plotting Histos

In [14]:
length = len(DFrameArray[4].iloc[0,:]) # Number of the columns

ColNames = list(DFrameArray[4]) # Names of the columns
print(ColNames)

['Nombre', 'ID', 'Nota1', 'A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'Nota2', 'A2', 'B2', 'C2', 'D2', 'E2', 'F2', 'Nota3', 'A3', 'B3', 'C3', 'D3', 'E3', 'F3', 'Nota4', 'A4', 'B4', 'C4', 'D4', 'E4', 'F4', 'Nota5', 'A5', 'B5', 'C5', 'D5', 'E5', 'F5']


In [15]:
def CreateHistoFig(Input, Cuts, Column, Name, Bins = 15, density_ = False):
    
    if Cuts:
        print('-- Plotting with Cuts ---', Name)
    else:
        print('-- Plotting ---', Name)
    
    Ylabel = r'N$\'u$mero de estudiantes'
    DFrame = Input[:]
    Font1 = 12
    
    
    
    fig = plt.figure(figsize=(10,10))
    
    ax1 = fig.add_subplot(2,2,1)
    if len(DFrame[0].index) != 0:
        n, bins, patches = ax1.hist(DFrame[0].iloc[:,Column], edgecolor='black', bins = Bins, density = density_, facecolor='blue', alpha=0.70, label='FISI-16')
        (mu, sigma) = norm.fit(DFrame[0].iloc[:,Column])
        y = scipy.stats.norm.pdf( bins, mu, sigma)
        ax1.plot(bins, y, 'r--', linewidth=3)
    #ax1.set_xlabel(Name, fontsize=Font1)
    ax1.set_ylabel(Ylabel, fontsize=Font1)
    ax1.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[0]))
    if Cuts:
        ax1.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[0]))  
    ax1.legend(loc=0)
    
    ax2 = fig.add_subplot(2,2,2)
    if len(DFrame[1].index) != 0:
        n, bins, patches = ax2.hist(DFrame[1].iloc[:,Column], edgecolor='black', bins = Bins, density = density_, facecolor='blue', alpha=0.70, label='FISI-17')
        (mu, sigma) = norm.fit(DFrame[1].iloc[:,Column])
        y = scipy.stats.norm.pdf( bins, mu, sigma)
        ax2.plot(bins, y, 'r--', linewidth=3)
        
    #ax2.set_xlabel(Name, fontsize=Font1)
    #ax2.set_ylabel(Ylabel, fontsize=Font1)
    ax2.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[1]))
    if Cuts:
        ax2.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[1]))  
    ax2.legend(loc=0)
    
    ax3 = fig.add_subplot(2,2,3)
    if len(DFrame[2].index) != 0:
        n, bins, patches = ax3.hist(DFrame[2].iloc[:,Column], edgecolor='black', bins = Bins, density = density_, facecolor='blue', alpha=0.70, label='FISI-18')
        (mu, sigma) = norm.fit(DFrame[2].iloc[:,Column])
        y = scipy.stats.norm.pdf( bins, mu, sigma)
        ax3.plot(bins, y, 'r--', linewidth=3)
        
    ax3.set_xlabel(Name, fontsize=Font1)
    ax3.set_ylabel(Ylabel, fontsize=Font1)
    
    ax3.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[2]))
    if Cuts:
        ax3.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[2]))  

    ax3.legend(loc=0)
    
    ax4 = fig.add_subplot(2,2,4)
    if len(DFrame[3].index) != 0:
        n, bins, patches = ax4.hist(DFrame[3].iloc[:,Column], edgecolor='black', bins = Bins, density = density_, facecolor='blue', alpha=0.70, label='FISI-19')
        (mu, sigma) = norm.fit(DFrame[3].iloc[:,Column])
        y = scipy.stats.norm.pdf( bins, mu, sigma)
        ax4.plot(bins, y, 'r--', linewidth=3)
        
    ax4.set_xlabel(Name, fontsize=Font1)
    #ax4.set_ylabel(Ylabel, fontsize=Font1)
    
    ax4.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[3]), fontsize=Font1)
    if Cuts:
        ax4.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[3]), fontsize=Font1)  
    
    ax4.legend(loc=0)
    
    NameF = 'Figures/Histos/Histo_' + Name + '.pdf'
    if Cuts:
        NameF = 'Figures/Histos/Histo_' + Name + '_Cuts.pdf'
    
   
    plt.savefig(NameF, dpi=120,bbox_inches='tight')
    plt.close()
    
    # Plot for the whole sample
    fig = plt.figure(figsize=(10,10))
    ax1 = fig.add_subplot(1,1,1)
    if len(DFrame[4].index) != 0:
        n, bins, patches = ax1.hist(DFrame[4].iloc[:,Column], edgecolor='black', bins = Bins, density = density_, facecolor='blue', alpha=0.70, label='FISICA-I')
        (mu, sigma) = norm.fit(DFrame[4].iloc[:,Column])
        y = scipy.stats.norm.pdf( bins, mu, sigma)
        ax1.plot(bins, y, 'r--', linewidth=3)
        
    ax1.set_xlabel(Name, fontsize=Font1)
    ax1.set_ylabel(Ylabel, fontsize=Font1)
   # ax1.set_xlim(0.,5.)
    ax1.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, Entries[4]), fontsize=Font1)
    if Cuts:
        ax1.set_title(r'$\mu=%.3f,\ \sigma=%.3f,\ Total=%.0f$' %(mu, sigma, EntriesCuts[4]), fontsize=Font1) 
    ax1.legend(loc=0)
    
    NameFT = 'Figures/Histos/Histo_' + Name + '_T.pdf'
    if Cuts:
        NameFT = 'Figures/Histos/Histo_' + Name + '_T_Cuts.pdf'
    
    plt.savefig(NameFT, dpi=120,bbox_inches='tight')
    plt.close()

In [ ]:
#For each column, a histogram is created...

for i in range(2,length):
#for i in range(2,22):
    CreateHistoFig(DFrameArray, False, i, ColNames[i], density_ = False)
    CreateHistoFig(DFrameArrayCuts, True, i, ColNames[i], density_ = False)

('-- Plotting ---', 'Nota1')
('-- Plotting with Cuts ---', 'Nota1')
('-- Plotting ---', 'A1')
('-- Plotting with Cuts ---', 'A1')
('-- Plotting ---', 'B1')
('-- Plotting with Cuts ---', 'B1')
('-- Plotting ---', 'C1')
('-- Plotting with Cuts ---', 'C1')
('-- Plotting ---', 'D1')


/home/alejandro/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1662: RuntimeWarning: divide by zero encountered in true_divide
  x = np.asarray((x - loc)/scale, dtype=dtyp)


('-- Plotting with Cuts ---', 'D1')
('-- Plotting ---', 'E1')
('-- Plotting with Cuts ---', 'E1')
('-- Plotting ---', 'F1')
('-- Plotting with Cuts ---', 'F1')
('-- Plotting ---', 'Nota2')
('-- Plotting with Cuts ---', 'Nota2')
('-- Plotting ---', 'A2')
('-- Plotting with Cuts ---', 'A2')
('-- Plotting ---', 'B2')
('-- Plotting with Cuts ---', 'B2')
('-- Plotting ---', 'C2')
('-- Plotting with Cuts ---', 'C2')
('-- Plotting ---', 'D2')
('-- Plotting with Cuts ---', 'D2')
('-- Plotting ---', 'E2')
('-- Plotting with Cuts ---', 'E2')
('-- Plotting ---', 'F2')
('-- Plotting with Cuts ---', 'F2')
('-- Plotting ---', 'Nota3')
('-- Plotting with Cuts ---', 'Nota3')
('-- Plotting ---', 'A3')


In [ ]:
from seaborn import countplot
from seaborn import scatterplot
scatterplot(x='Nota3', y='A3',hue='ID', data=DFrameArray[4])
#countplot(x='A1',hue='ID', data=DFrameArray[0])

In [ ]:
NewFrameA = DFrameArray[4].filter(items=['ID','A1','A2','A3','A4'])
NewFrameB = DFrameArray[4].filter(items=['ID','B1','B2','B3','B4'])
NewFrameC = DFrameArray[4].filter(items=['ID','C1','C2','C3','C4'])
NewFrameD = DFrameArray[4].filter(items=['ID','D1','D2','D3','D4'])
NewFrameE = DFrameArray[4].filter(items=['ID','E1','E2','E3','E4'])
NewFrameF = DFrameArray[4].filter(items=['ID','F1','F2','F3','F4'])
NewFrameN = DFrameArray[4].filter(items=['ID','Nota1','Nota2','Nota3','Nota4'])


length = len(NewFrameA.iloc[0,:])
students = len(NewFrameA.iloc[:,0])

print(students)

for i in range(students):
    
    print('--- creating for: ', NewFrameA.iloc[i,0])
    
    #if i != 0:
    #    continue
        
    
    
    fig = plt.figure(figsize=(14,10))
    fig.suptitle(str(NewFrameA.iloc[i,0]), fontsize=15)
    
    ax1 = fig.add_subplot(3,3,1) 
    ax2 = fig.add_subplot(3,3,2) 
    ax3 = fig.add_subplot(3,3,3)
    ax4 = fig.add_subplot(3,3,4)
    ax5 = fig.add_subplot(3,3,5)
    ax6 = fig.add_subplot(3,3,6)
    
    ax7 = fig.add_subplot(3,1,3)
        
    NumNota = []
    A = [] 
    B = [] 
    C = [] 
    D = []
    E = []
    F = []
    N = []

    for j in range(1,length):
        NumNota.append(j)
        A.append(NewFrameA.iloc[i,j])
        B.append(NewFrameB.iloc[i,j])
        C.append(NewFrameC.iloc[i,j])
        D.append(NewFrameD.iloc[i,j])
        E.append(NewFrameE.iloc[i,j])
        F.append(NewFrameF.iloc[i,j])
        N.append(NewFrameN.iloc[i,j])

    
    ax1.plot(NumNota,A,'ko',markersize=12,label=NewFrameA.iloc[i,0])
    ax2.plot(NumNota,B,'bo',markersize=12,label=NewFrameA.iloc[i,0])
    ax3.plot(NumNota,C,'ro',markersize=12,label=NewFrameA.iloc[i,0])
    ax4.plot(NumNota,D,'go',markersize=12,label=NewFrameA.iloc[i,0])
    ax5.plot(NumNota,E,'yo',markersize=12,label=NewFrameA.iloc[i,0])
    ax6.plot(NumNota,F,'bo',markersize=12,label=NewFrameA.iloc[i,0])
    
    ax7.plot(NumNota,N,'ko',markersize=12,label=NewFrameA.iloc[i,0])
    
    ax1.set_ylabel(r'$A$',fontsize=15)
    ax2.set_ylabel(r'$B$',fontsize=15)
    ax3.set_ylabel(r'$C$',fontsize=15)
    ax4.set_ylabel(r'$D$',fontsize=15)
    ax5.set_ylabel(r'$E$',fontsize=15)
    ax6.set_ylabel(r'$F$',fontsize=15)
    
    ax7.set_ylabel(r'$Nota$',fontsize=15)
    ax7.set_xlabel(r'N$\'u$mero de Semana', fontsize=15)
    
    ax1.set_ylim(-0.1,1.1)
    ax2.set_ylim(-0.1,1.1)
    ax3.set_ylim(-0.1,1.1)
    ax4.set_ylim(-0.1,1.1)
    ax5.set_ylim(-0.1,1.1)
    ax6.set_ylim(-0.1,1.1)
    
    ax7.set_ylim(-0.1,5.1)
    
   # ax1.legend(loc=1)
   # ax2.legend(loc=1)
   ## ax3.legend(loc=1)
    #ax4.legend(loc=1)
   # ax5.legend(loc=1)
    
    file_ = 'Figures/Students/'+ str(NewFrameA.iloc[i,0]) +'.png'
    
    plt.savefig(file_)
    plt.close()

In [ ]:
!convert Figures/Students/*.png -loop 0 -delay 20000 Students.gif

In [ ]:
print(DFrameArray[1].iloc[0,:])

In [ ]:
DFrameArray[0].filter(items=['ID','A1','A2','A3','A4'],axis=1)

In [ ]:
fig = plt.figure(figsize=(50,10))

ax1 = fig.add_subplot(2,2,1)
ax1 = DFrameArray[4].groupby('A1')['A1'].sum().plot(kind='pie', fontsize=15)
ax2 = fig.add_subplot(2,2,3)
ax2 = DFrameArray[4].groupby('A1')['A2'].sum().plot(kind='pie', fontsize=15)

plt.show()

In [ ]:
#fig = plt.figure()
sns.lmplot(x='A2',y='A1',data=DFrameArray[4],fit_reg=False,hue='ID',legend=True,palette='viridis')
#plt.savefig('Figures/A1seaborn.pdf',dpi=100,bbox_inches='tight')

In [ ]:
# Uso de filtros por columna
#DFrameArray[0].filter(items=['ID','A1','A2'])
#DFrameArray[1].filter(like='A',axis=1)


# Seleccion por filar
#DFrameArray[2].set_index('A1')

#print(DFrameArray[2].loc[0:3])
#print(DFrameArray[2].iloc[:,0:2])

#print(DFrameArray[0]['Nota1'])
#print(dft['A1'])

In [ ]:
# Agregar columna

Sum = 0

for i in range(1,2):
    Sum += DFrameArray[0]['A'+str(i)]

dtest = DFrameArray[0].assign(NotaFinal=Sum.values)
print(dtest)

In [ ]:
# Mirar posicion
print(dtest.iat[0,1])
# Cambiar posicion
##dtest.iat[0,1] = 3.
#print(dtest)


# Agregar columna o fila 
#dtest.loc['Suma x columna'] = dtest.sum(axis=0)
#dtest.loc[:,'Suma x Renglon'] = dtest.sum(axis=1)
#print(dtest)

In [ ]:
# Plotting pies


sizes = DFrameArray[0]['A1'].value_counts()
print(sizes)
pie = DFrameArray[0]['A1'].value_counts().plot(kind='pie', shadow=True,\
                                              autopct='%1.1f%%', startangle=30,\
                                              radius=1.5,center=(0.5,0.5),\
                                              textprops={'fontsize':12},frame=False,\
                                              pctdistance=0.65)
pie.set_ylabel('')
pie.set_xlabel('')


labels=sizes.index.unique()
plt.gca().axis('equal')
plt.title(DFrameArray[0].columns[3], weight='bold',size=14)
plt.legend(labels, bbox_to_anchor=(0.,1.1))


plt.savefig('Figures/A1.pdf',dpi=100,bbox_inches='tight')


In [ ]:
fig = plt.figure()

DFrameArray[4].ID.groupby(DFrameArray[4].Nota1).sum().plot(kind='pie',cmap='viridis')
plt.axis('equal')
plt.ylabel('')
plt.savefig('Figures/A1Pie.pdf',dpi=100,bbox_inches='tight')

In [ ]:
#fig = plt.figure()
sns.lmplot(x='Nota1',y='C1',data=DFrameArray[2],fit_reg=False,hue='B1',legend=False,palette='viridis')
#plt.savefig('Figures/A1seaborn.pdf',dpi=100,bbox_inches='tight')

In [ ]:
#sns.set(style='ticks', color_codes=True)
#g = sns.pairplot(DFrameArray[2], hue='ID', palette='Spectral')

In [ ]:
# Write the whole dataframe in an excel file


output = pd.ExcelWriter('DataBaseFisicaI.xls')
DFrameArrayCuts[4].to_excel(output,'Hoja1')
output.save()